app = "test"

[server]
host = "0.0.0.0"
port = 8081

[mysql]
dsn = "root:root@(localhost:3306)/erp?timeout=5000ms&readTimeout=10s&charset=utf8mb4"
maxIdle = 10
maxOpen = 100
maxIdleTime = "10s"
maxLifeTime = "1h"

[cache]
host = "127.0.0.1"
port = 6379

[middleware]
response_trace_id = false
